### ISSUE TITLE
Daemon crash

### ISSUE THREAD

**Issue by joula** [tableflip/guvnor#42]
I use guvnor inside a docker container and run 4 processes. Everything seems fine for about a half day or so. I can see that the memory usage of the Node.js apps go up as the time goes by on the web UI. And next day when I check the the web UI I don't see the server in the list and when I check the server the guvnor daemon is not running. There is nothing special in the /var/log/guvnor directory. Is there any way I can find out what causes the crash? The docker container is limited to use 2G memory. Thanks.

**Comment by achingbrain** [comment]
That's interesting, what command do you use to run it inside Docker? I ask because #39 is about a no-daemon mode so it can be used inside Docker...

Anyway - Docker will kill -9 a process that consumes too much memory, so if there's nothing in /var/log/guvnor it may be what happened.

To debug the memory leak, use the web interface or `guv heapdump` to take heap dumps from the processes at regular intervals (every hour for example) and compare them using the profiles tab of Chrome's debug tools.  It should show you which objects are being allocated but not garbage collected.  If you can track down where they are being created you've found the leak.

**Comment by joula** [comment]
Thanks for the quick response. I will check and update the issue.

**Comment by joula** [comment]
Snippet from dockerfile:

# --- GUVNOR ---
# Install package
RUN npm install -g guvnor --unsafe-perm

# Copy guvnor config file
ADD ./docker/guvnor/guvnorrc /etc/guvnor/guvnorrc
ADD ./docker/guvnor/users.json /etc/guvnor/users.json

# Start guvnor on boot
RUN ln -s /usr/lib/node_modules/guvnor/scripts/init/sysv/guvnor /etc/init.d/guvnor
RUN update-rc.d guvnor defaults

This is how I add the process (in start.sh):
guv start -n Client app.js

**Comment by joula** [comment]
Basically I use a dummy command to keep the docker container running. So the no-daemon mode would be really good. Also having memory limitation for each processes would be really nice. So if a process reaches a given amount of memory it should be restarted.

**Comment by goloroden** [comment]
Just out of curiosity: What dummy command are you using?

**Comment by joula** [comment]
I know that it is not good but I am using an "empty" http server.

**Comment by joula** [comment]
Closing the issue since it was not related to guvnor but some kind of memory leak in the code and docker  behavior.
